# defines the final state probability needed for a state to be accepting
beta: 0.90

# number of symbols in pdfa alphabet
alphabet_size: 2

# number of states in pdfa state space
num_states: 4

# symbol to use as the transition to a final state
final_transition_sym: -1

# unique start state string label of pdfa
start_state: 'q0'

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'q0':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q1':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q2':
    final_probability: 0.00
    trans_distribution: null
    is_accepting: null

  'q3':
    final_probability: 1.00
    trans_distribution: null
    is_accepting: null

# define the edges of the graph
edges:

  'q0':

    'q1':
      symbols:
        - 1
      probabilities:
        - 0.7

    'q2':
      symbols:
        - 2
      probabilities:
        - 0.3

  'q1':

    'q3':
      symbols:
        - 2
      probabilities:
        - 1.00

  'q2':

    'q3':
      symbols:
        - 1
      probabilities:
        - 1.00

  'q3':