# number of symbols in TS alphabet
alphabet_size: 2

# number of states in TS state space
num_states: 4

# number of discrete state observations in TS obs. space
num_obs: 2

# unique start state string label of TS
start_state: 'x1'

# symbol to use as the transition to a final state
final_transition_sym: -1

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'x1':
    observation: 'a'
  
  'x2':
    observation: 'a'

  'x3':
    observation: 'b'

  'x4':
    observation: 'a'


# define the edges of the graph
edges:

  'x1':

    'x2':
      symbols:
        - 's1'

    'x4':
      symbols:
        - 's2'

  'x2':

    'x3':
      symbols:
        - 's1'